behaviors:
  Paca:
    trainer_type: ppo
    max_steps:           10000000
    checkpoint_interval: 500000
    keep_checkpoints:    10
    summary_freq:        20000
    time_horizon:        512
    threaded:            true
    
    hyperparameters:
      batch_size: 500
      buffer_size: 5000
      learning_rate: 0.0005 # 1e-5 - 1e-3
      beta: 0.005 # 1e-4 - 1e-2
      epsilon: 0.25 # 0.1 - 0.3
      lambd: 0.95 # 0.9 - 0.95
      num_epoch: 3 # 3 - 10
      learning_rate_schedule: linear
      
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
      #  strength: 0.003
      #  gamma: 0.99
      #  encoding_size: 64
      #  learning_rate: 0.005

